version: '3'

services:
  db:
    env_file:
      - .env.${NODE_ENV}
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_HOST_AUTH_METHOD=trust
    container_name: ferreiradb
    volumes:
      - ./postgres:/var/lib/postgresql/data
